# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
#            pattern: ^/command/
            pattern: ^/
            anonymous: true
            http_basic:
                realm: "Acces restricted"
                provider: fos_userbundle
        main:
#            anonymous: ~
            pattern: ^/
            form_login:
                default_target_path: /voyage/tableau-de-bord
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/, role: ROLE_USER }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/navbar, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ideas-of-travels, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/share, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/voyage, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/crud, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/command/, role: ROLE_SUPER_ADMIN }
