# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    assetic.value_supplier.class: AppBundle\Assetic\CustomValueSupplier
#    parameter_name: value

services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }


#    fos_comment.form_type.comment.default:
#        class: AppCommentBundle\Form\CommentType
#        arguments:
#            - %fos_comment.model.comment.class%
#        tags:
#            - { name: form.type, alias: fos_comment_comment }

