homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:homepage }


country:
    path: /country/{slugCountry}
    defaults:  { _controller: AppBundle:Destination:viewCountry }

destination:
    path: /destination/{slugDestination}
    defaults:  { _controller: AppBundle:Destination:viewDestination }
