services:
    app.twig_extension:
        class: AppBundle\Twig\AssetExistsExtension
        arguments:
            - "@kernel"
        public: false
        tags:
            - { name: twig.extension }

    maplace_marker_builder:
        class : AppBundle\Service\MaplaceMarkerBuilder
        arguments:
            - "@twig"
