services:
    voyage_stats:
        class : CalculatorBundle\Service\Stats\VoyageStats
        arguments:
            - @twig

    best_journey_finder:
        class: CalculatorBundle\Service\Journey\BestJourneyFinder

    crud_stage:
        class : CalculatorBundle\Service\CRUD\CRUDStage
        arguments:
            - @doctrine.orm.entity_manager
            - @best_journey_finder

    crud_voyage:
        class : CalculatorBundle\Service\CRUD\CRUDVoyage
        arguments:
            - @doctrine.orm.entity_manager
            - @google_url_shortener_api

    voyage_service:
        class : CalculatorBundle\Service\VoyageService
        arguments:
            - @doctrine.orm.entity_manager
            - @maplace_marker_builder

    google_url_shortener_api:
        class : CalculatorBundle\Service\GoogleUrlShortener\GoogleUrlShortenerApi
        arguments:
            - %api_google_key%
            - @router
